<?php

use Illuminate\Database\Seeder;

class PostSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        \App\Post::create([
        	'title' => "Laravel Latest News",
        	'slug' => "laravel-latest-news",
        	'content' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis egestas ipsum lorem, a dictum justo tincidunt vitae. Ut efficitur ante eu orci suscipit feugiat. Nullam nec lectus eros. Duis et accumsan orci. Cras urna dolor, facilisis sit amet eleifend vel, sagittis id ipsum. Sed mattis tempus nibh, facilisis molestie tellus. Nunc commodo nec magna sed mattis. Sed laoreet, nulla quis eleifend pharetra, magna enim commodo nisl, ac tempor enim ex in elit. Maecenas et tempus eros, ut rutrum nisl. Cras luctus maximus aliquam.\r\n\r\nFusce dignissim tempor aliquam. Sed blandit dictum ultricies. Donec et tincidunt tortor, in ultrices lorem. Aliquam erat volutpat. Suspendisse potenti. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam sollicitudin orci eu mi maximus, quis maximus nisi placerat. Suspendisse a eros porttitor, vulputate nisl posuere, imperdiet neque. Curabitur tempor lacus urna, et posuere neque consectetur et. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In hac habitasse platea dictumst.\r\n\r\nPhasellus ut nisi quis lectus interdum dignissim. In tristique molestie est et elementum. Suspendisse potenti. Etiam accumsan sagittis ornare. Pellentesque a sapien vel mauris dignissim laoreet et quis risus. Morbi enim odio, finibus at erat porttitor, congue pretium urna. Pellentesque urna leo, fringilla sed vulputate at, dignissim vel velit. Etiam varius nulla augue, ac faucibus massa facilisis eget. Ut non justo tortor. Nulla quis enim nisi. Donec porta ac enim et vehicula.\r\n\r\nMorbi ut leo tortor. Fusce dictum et metus et convallis. Vivamus cursus pellentesque odio ac vulputate. Phasellus sagittis feugiat consectetur. Donec aliquam venenatis nisi, ut egestas nibh convallis vehicula. Morbi scelerisque sagittis pellentesque. Ut dapibus lorem urna, sit amet auctor tortor elementum at. Nullam id nibh dignissim, convallis nisl eu, scelerisque urna.\r\n\r\nMaecenas lectus orci, ornare at ligula tincidunt, porttitor lobortis lorem. Nullam sit amet suscipit sapien, non rhoncus urna. Nullam eget nunc lectus. Sed sodales magna sit amet arcu molestie congue. Integer eu sapien sed libero pellentesque consequat quis vel erat. Vestibulum eu metus condimentum, dictum libero vitae, consectetur leo. Maecenas et urna lacinia lacus lacinia dictum. Vivamus convallis blandit justo, et tristique tellus convallis quis. Mauris sollicitudin sapien in venenatis dapibus. Aliquam placerat mauris at diam condimentum, ut ultricies augue porta. Sed fermentum non eros vitae cursus. Integer odio lacus, commodo eu gravida vitae, vehicula eget erat. Aliquam vitae feugiat dui. Cras varius ultricies tortor, vel tristique purus tempor id. Curabitur at varius massa.",
        	'category_id' => 1,
        	'featured' => 'uploads/posts/15110938056.jpg',
        	'deleted_at' => NULL,
			'created_at' => '2019-02-18 15:53:08',
			'updated_at' => '2019-02-18 15:53:08',
			'user_id' => 1
        ]);
        \App\Post::create([
        	'title' => "Laravel Latest News",
        	'slug' => "laravel-latest-news",
        	'content' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis egestas ipsum lorem, a dictum justo tincidunt vitae. Ut efficitur ante eu orci suscipit feugiat. Nullam nec lectus eros. Duis et accumsan orci. Cras urna dolor, facilisis sit amet eleifend vel, sagittis id ipsum. Sed mattis tempus nibh, facilisis molestie tellus. Nunc commodo nec magna sed mattis. Sed laoreet, nulla quis eleifend pharetra, magna enim commodo nisl, ac tempor enim ex in elit. Maecenas et tempus eros, ut rutrum nisl. Cras luctus maximus aliquam.\r\n\r\nFusce dignissim tempor aliquam. Sed blandit dictum ultricies. Donec et tincidunt tortor, in ultrices lorem. Aliquam erat volutpat. Suspendisse potenti. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam sollicitudin orci eu mi maximus, quis maximus nisi placerat. Suspendisse a eros porttitor, vulputate nisl posuere, imperdiet neque. Curabitur tempor lacus urna, et posuere neque consectetur et. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In hac habitasse platea dictumst.\r\n\r\nPhasellus ut nisi quis lectus interdum dignissim. In tristique molestie est et elementum. Suspendisse potenti. Etiam accumsan sagittis ornare. Pellentesque a sapien vel mauris dignissim laoreet et quis risus. Morbi enim odio, finibus at erat porttitor, congue pretium urna. Pellentesque urna leo, fringilla sed vulputate at, dignissim vel velit. Etiam varius nulla augue, ac faucibus massa facilisis eget. Ut non justo tortor. Nulla quis enim nisi. Donec porta ac enim et vehicula.\r\n\r\nMorbi ut leo tortor. Fusce dictum et metus et convallis. Vivamus cursus pellentesque odio ac vulputate. Phasellus sagittis feugiat consectetur. Donec aliquam venenatis nisi, ut egestas nibh convallis vehicula. Morbi scelerisque sagittis pellentesque. Ut dapibus lorem urna, sit amet auctor tortor elementum at. Nullam id nibh dignissim, convallis nisl eu, scelerisque urna.\r\n\r\nMaecenas lectus orci, ornare at ligula tincidunt, porttitor lobortis lorem. Nullam sit amet suscipit sapien, non rhoncus urna. Nullam eget nunc lectus. Sed sodales magna sit amet arcu molestie congue. Integer eu sapien sed libero pellentesque consequat quis vel erat. Vestibulum eu metus condimentum, dictum libero vitae, consectetur leo. Maecenas et urna lacinia lacus lacinia dictum. Vivamus convallis blandit justo, et tristique tellus convallis quis. Mauris sollicitudin sapien in venenatis dapibus. Aliquam placerat mauris at diam condimentum, ut ultricies augue porta. Sed fermentum non eros vitae cursus. Integer odio lacus, commodo eu gravida vitae, vehicula eget erat. Aliquam vitae feugiat dui. Cras varius ultricies tortor, vel tristique purus tempor id. Curabitur at varius massa.",
        	'category_id' => 1,
        	'featured' => 'uploads/posts/15110938056.jpg',
        	'deleted_at' => NULL,
			'created_at' => '2019-02-18 15:53:08',
			'updated_at' => '2019-02-18 15:53:08',
			'user_id' => 1
        ]);
        \App\Post::create([
        	'title' => "Laravel Latest News",
        	'slug' => "laravel-latest-news",
        	'content' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis egestas ipsum lorem, a dictum justo tincidunt vitae. Ut efficitur ante eu orci suscipit feugiat. Nullam nec lectus eros. Duis et accumsan orci. Cras urna dolor, facilisis sit amet eleifend vel, sagittis id ipsum. Sed mattis tempus nibh, facilisis molestie tellus. Nunc commodo nec magna sed mattis. Sed laoreet, nulla quis eleifend pharetra, magna enim commodo nisl, ac tempor enim ex in elit. Maecenas et tempus eros, ut rutrum nisl. Cras luctus maximus aliquam.\r\n\r\nFusce dignissim tempor aliquam. Sed blandit dictum ultricies. Donec et tincidunt tortor, in ultrices lorem. Aliquam erat volutpat. Suspendisse potenti. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam sollicitudin orci eu mi maximus, quis maximus nisi placerat. Suspendisse a eros porttitor, vulputate nisl posuere, imperdiet neque. Curabitur tempor lacus urna, et posuere neque consectetur et. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In hac habitasse platea dictumst.\r\n\r\nPhasellus ut nisi quis lectus interdum dignissim. In tristique molestie est et elementum. Suspendisse potenti. Etiam accumsan sagittis ornare. Pellentesque a sapien vel mauris dignissim laoreet et quis risus. Morbi enim odio, finibus at erat porttitor, congue pretium urna. Pellentesque urna leo, fringilla sed vulputate at, dignissim vel velit. Etiam varius nulla augue, ac faucibus massa facilisis eget. Ut non justo tortor. Nulla quis enim nisi. Donec porta ac enim et vehicula.\r\n\r\nMorbi ut leo tortor. Fusce dictum et metus et convallis. Vivamus cursus pellentesque odio ac vulputate. Phasellus sagittis feugiat consectetur. Donec aliquam venenatis nisi, ut egestas nibh convallis vehicula. Morbi scelerisque sagittis pellentesque. Ut dapibus lorem urna, sit amet auctor tortor elementum at. Nullam id nibh dignissim, convallis nisl eu, scelerisque urna.\r\n\r\nMaecenas lectus orci, ornare at ligula tincidunt, porttitor lobortis lorem. Nullam sit amet suscipit sapien, non rhoncus urna. Nullam eget nunc lectus. Sed sodales magna sit amet arcu molestie congue. Integer eu sapien sed libero pellentesque consequat quis vel erat. Vestibulum eu metus condimentum, dictum libero vitae, consectetur leo. Maecenas et urna lacinia lacus lacinia dictum. Vivamus convallis blandit justo, et tristique tellus convallis quis. Mauris sollicitudin sapien in venenatis dapibus. Aliquam placerat mauris at diam condimentum, ut ultricies augue porta. Sed fermentum non eros vitae cursus. Integer odio lacus, commodo eu gravida vitae, vehicula eget erat. Aliquam vitae feugiat dui. Cras varius ultricies tortor, vel tristique purus tempor id. Curabitur at varius massa.",
        	'category_id' => 1,
        	'featured' => 'uploads/posts/15110938056.jpg',
        	'deleted_at' => NULL,
			'created_at' => '2019-02-18 15:53:08',
			'updated_at' => '2019-02-18 15:53:08',
			'user_id' => 1
        ]);
        \App\Post::create([
        	'title' => "Laravel Latest News",
        	'slug' => "laravel-latest-news",
        	'content' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis egestas ipsum lorem, a dictum justo tincidunt vitae. Ut efficitur ante eu orci suscipit feugiat. Nullam nec lectus eros. Duis et accumsan orci. Cras urna dolor, facilisis sit amet eleifend vel, sagittis id ipsum. Sed mattis tempus nibh, facilisis molestie tellus. Nunc commodo nec magna sed mattis. Sed laoreet, nulla quis eleifend pharetra, magna enim commodo nisl, ac tempor enim ex in elit. Maecenas et tempus eros, ut rutrum nisl. Cras luctus maximus aliquam.\r\n\r\nFusce dignissim tempor aliquam. Sed blandit dictum ultricies. Donec et tincidunt tortor, in ultrices lorem. Aliquam erat volutpat. Suspendisse potenti. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam sollicitudin orci eu mi maximus, quis maximus nisi placerat. Suspendisse a eros porttitor, vulputate nisl posuere, imperdiet neque. Curabitur tempor lacus urna, et posuere neque consectetur et. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In hac habitasse platea dictumst.\r\n\r\nPhasellus ut nisi quis lectus interdum dignissim. In tristique molestie est et elementum. Suspendisse potenti. Etiam accumsan sagittis ornare. Pellentesque a sapien vel mauris dignissim laoreet et quis risus. Morbi enim odio, finibus at erat porttitor, congue pretium urna. Pellentesque urna leo, fringilla sed vulputate at, dignissim vel velit. Etiam varius nulla augue, ac faucibus massa facilisis eget. Ut non justo tortor. Nulla quis enim nisi. Donec porta ac enim et vehicula.\r\n\r\nMorbi ut leo tortor. Fusce dictum et metus et convallis. Vivamus cursus pellentesque odio ac vulputate. Phasellus sagittis feugiat consectetur. Donec aliquam venenatis nisi, ut egestas nibh convallis vehicula. Morbi scelerisque sagittis pellentesque. Ut dapibus lorem urna, sit amet auctor tortor elementum at. Nullam id nibh dignissim, convallis nisl eu, scelerisque urna.\r\n\r\nMaecenas lectus orci, ornare at ligula tincidunt, porttitor lobortis lorem. Nullam sit amet suscipit sapien, non rhoncus urna. Nullam eget nunc lectus. Sed sodales magna sit amet arcu molestie congue. Integer eu sapien sed libero pellentesque consequat quis vel erat. Vestibulum eu metus condimentum, dictum libero vitae, consectetur leo. Maecenas et urna lacinia lacus lacinia dictum. Vivamus convallis blandit justo, et tristique tellus convallis quis. Mauris sollicitudin sapien in venenatis dapibus. Aliquam placerat mauris at diam condimentum, ut ultricies augue porta. Sed fermentum non eros vitae cursus. Integer odio lacus, commodo eu gravida vitae, vehicula eget erat. Aliquam vitae feugiat dui. Cras varius ultricies tortor, vel tristique purus tempor id. Curabitur at varius massa.",
        	'category_id' => 1,
        	'featured' => 'uploads/posts/15110938056.jpg',
        	'deleted_at' => NULL,
			'created_at' => '2019-02-18 15:53:08',
			'updated_at' => '2019-02-18 15:53:08',
			'user_id' => 1
        ]);
        \App\Post::create([
        	'title' => "Laravel Latest News",
        	'slug' => "laravel-latest-news",
        	'content' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis egestas ipsum lorem, a dictum justo tincidunt vitae. Ut efficitur ante eu orci suscipit feugiat. Nullam nec lectus eros. Duis et accumsan orci. Cras urna dolor, facilisis sit amet eleifend vel, sagittis id ipsum. Sed mattis tempus nibh, facilisis molestie tellus. Nunc commodo nec magna sed mattis. Sed laoreet, nulla quis eleifend pharetra, magna enim commodo nisl, ac tempor enim ex in elit. Maecenas et tempus eros, ut rutrum nisl. Cras luctus maximus aliquam.\r\n\r\nFusce dignissim tempor aliquam. Sed blandit dictum ultricies. Donec et tincidunt tortor, in ultrices lorem. Aliquam erat volutpat. Suspendisse potenti. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam sollicitudin orci eu mi maximus, quis maximus nisi placerat. Suspendisse a eros porttitor, vulputate nisl posuere, imperdiet neque. Curabitur tempor lacus urna, et posuere neque consectetur et. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In hac habitasse platea dictumst.\r\n\r\nPhasellus ut nisi quis lectus interdum dignissim. In tristique molestie est et elementum. Suspendisse potenti. Etiam accumsan sagittis ornare. Pellentesque a sapien vel mauris dignissim laoreet et quis risus. Morbi enim odio, finibus at erat porttitor, congue pretium urna. Pellentesque urna leo, fringilla sed vulputate at, dignissim vel velit. Etiam varius nulla augue, ac faucibus massa facilisis eget. Ut non justo tortor. Nulla quis enim nisi. Donec porta ac enim et vehicula.\r\n\r\nMorbi ut leo tortor. Fusce dictum et metus et convallis. Vivamus cursus pellentesque odio ac vulputate. Phasellus sagittis feugiat consectetur. Donec aliquam venenatis nisi, ut egestas nibh convallis vehicula. Morbi scelerisque sagittis pellentesque. Ut dapibus lorem urna, sit amet auctor tortor elementum at. Nullam id nibh dignissim, convallis nisl eu, scelerisque urna.\r\n\r\nMaecenas lectus orci, ornare at ligula tincidunt, porttitor lobortis lorem. Nullam sit amet suscipit sapien, non rhoncus urna. Nullam eget nunc lectus. Sed sodales magna sit amet arcu molestie congue. Integer eu sapien sed libero pellentesque consequat quis vel erat. Vestibulum eu metus condimentum, dictum libero vitae, consectetur leo. Maecenas et urna lacinia lacus lacinia dictum. Vivamus convallis blandit justo, et tristique tellus convallis quis. Mauris sollicitudin sapien in venenatis dapibus. Aliquam placerat mauris at diam condimentum, ut ultricies augue porta. Sed fermentum non eros vitae cursus. Integer odio lacus, commodo eu gravida vitae, vehicula eget erat. Aliquam vitae feugiat dui. Cras varius ultricies tortor, vel tristique purus tempor id. Curabitur at varius massa.",
        	'category_id' => 1,
        	'featured' => 'uploads/posts/15110938056.jpg',
        	'deleted_at' => NULL,
			'created_at' => '2019-02-18 15:53:08',
			'updated_at' => '2019-02-18 15:53:08',
			'user_id' => 1
        ]);
    }
}
